bookmark_highlight_color: '#64C8FF'
highlight_terms:
- bold: true
  color: '#6495ed'
  term: warn
- err
- bold: true
  color: '#FF0000'
  term: fatal
  text_color: '#FFFFFF'
- color: '#FFAA00'
  term: alert
  text_color: '#000000'
- bold: true
  color: '#800080'
  term: fail
- bold: false
  term: installing
  text_color: '#00FF00'
- bold: true
  color: '#0066CC'
  term: running
  text_color: '#FFFF00'
line_numbers_enabled: false
line_wrap_enabled: false
theme: dark
