name: Build Flatpak Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v3.1.0)'
        required: true
        default: 'v3.1.0'

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Flatpak and flatpak-builder
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder
        
    - name: Add Flathub repository
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        
    - name: Install required Flatpak runtime and SDK
      run: |
        sudo flatpak install -y flathub org.freedesktop.Platform//23.08
        sudo flatpak install -y flathub org.freedesktop.Sdk//23.08
        
    - name: Extract version from tag
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.tag }}"
        else
          VERSION="${GITHUB_REF#refs/tags/}"
        fi
        VERSION_NUMBER=${VERSION#v}
        echo "version=$VERSION_NUMBER" >> $GITHUB_OUTPUT
        echo "tag=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION_NUMBER"
        
    - name: Update Build_Version file
      run: |
        echo "VERSION=${{ steps.get_version.outputs.version }}" > rpmbuild/SOURCES/Build_Version
        
    - name: Prepare build environment
      run: |
        mkdir -p flatpak-build flatpak-repo
        
    - name: Build Flatpak package
      run: |
        flatpak-builder --user --install-deps-from=flathub --repo=flatpak-repo flatpak-build com.michettetech.LogViewer.yaml
        
    - name: Create Flatpak bundle
      run: |
        flatpak build-bundle flatpak-repo LogViewer-${{ steps.get_version.outputs.version }}.flatpak com.michettetech.LogViewer
        
    - name: Verify Flatpak bundle
      run: |
        ls -la LogViewer-${{ steps.get_version.outputs.version }}.flatpak
        file LogViewer-${{ steps.get_version.outputs.version }}.flatpak
        
    - name: Upload Flatpak artifact
      uses: actions/upload-artifact@v4
      with:
        name: flatpak-package
        path: LogViewer-${{ steps.get_version.outputs.version }}.flatpak
        retention-days: 30
        
    - name: Upload to release (if tag push)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: LogViewer-${{ steps.get_version.outputs.version }}.flatpak
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
