# GitHub Workflow for macOS App Bundle and DMG Creation
name: Build macOS App

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - log-viewer-windows-test
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    environment: deploy
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install system dependencies
        run: |
          # Install system dependencies if needed
          brew install --quiet create-dmg || true
          
      - name: Create macOS App Bundle
        run: |
          cd rpmbuild/SOURCES
          bash Build_App_MacOS.sh
          
      - name: Create DMG Package
        run: |
          cd rpmbuild/SOURCES
          bash Create_DMG_MacOS.sh
          
      - name: Upload App Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LogViewer-macOS-App
          path: rpmbuild/SOURCES/dist/Log Viewer.app
          retention-days: 30
          
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LogViewer-macOS-DMG
          path: rpmbuild/SOURCES/LogViewer-3.0.0-macOS.dmg
          retention-days: 30
          
      - name: Create Release Draft (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Log Viewer ${{ github.ref_name }}
          draft: true
          body: |
            ## Log Viewer ${{ github.ref_name }} - macOS Release
            
            ### Features
            - Cross-platform log file viewer
            - Support for .log, .out, .txt files
            - ANSI color support
            - Configurable highlighting
            - Fast search functionality
            - Dark theme interface
            
            ### macOS Installation
            1. Download the DMG file below
            2. Open the DMG file
            3. Drag "Log Viewer.app" to Applications folder
            4. Launch from Applications or Launchpad
            
            ### System Requirements
            - macOS 10.14 (Mojave) or later
            - 64-bit Intel or Apple Silicon Mac
            
            ### Configuration
            - Configuration files stored in `~/Library/Application Support/LogViewer/`
            - Supports custom highlighting configurations
            - Retina display optimized
            
            ### Support
            - Email: tmichett@redhat.com
            - Organization: Michette Technologies
          files: |
            rpmbuild/SOURCES/LogViewer-3.0.0-macOS.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Test App Bundle
        run: |
          cd rpmbuild/SOURCES
          # Test that the app bundle can be opened
          open "dist/Log Viewer.app" --args --help &
          sleep 5
          pkill -f "log_viewer" || true
          
          # Test DMG can be mounted
          hdiutil attach "LogViewer-3.0.0-macOS.dmg" -readonly -noautoopen
          sleep 2
          hdiutil detach "/Volumes/Log Viewer 3.0.0"
          
          echo "macOS build and packaging completed successfully!" 